[package]
name = "minato"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-contract = "0.1.0"
alloy-json-rpc = "0.1.0"
alloy-provider = "0.1.0"
reqwest = "0.11.10"
serde_json = "1.0.64"
alloy-provider = "0.1.0"
