[package]
name = "minato"
version = "0.1.0"
edition = "2021"

[profile.dev]​
​opt-level = 1 ​# 1 for minimal optimization and good debugging.

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.10"
